#! /bin/bash

projectDirSocp="./Lib/socp/"
buildDirSocp="./Lib/socp/build/Release/"
binDirSocp="./Lib/socp/bin/"

projectDirMinTime="./Lib/minTimeGradientMex/"
buildDirMinTime="./Lib/minTimeGradientMex/build/Release/"
binDirMinTime="./Lib/minTimeGradientMex/bin/"


# SOCP
cmake -S "$projectDirSocp" -B "$buildDirSocp" -DCMAKE_BUILD_TYPE=Release

cd "$buildDirSocp"

make


# MinTimeGradient
cd "../../../../"
cd "$buildDirMinTime"
cmake -S "$projectDirMinTime" -B "$buildDirMinTime" -DCMAKE_BUILD_TYPE=Release

cd "$buildDirMinTime"

make
